server:
  port: ${SERVICE_PORT}
  servlet:
    context-path: /authentication
spring:
  application:
    name: auth-service
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}/${DB_NAME}
    driver-class-name: org.postgresql.Driver

token:
  signing:
    key: ${SECRET_KEY}